config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get "tasks/new", to: "tasks#new", as: :new
    get "tasks", to: "tasks#index", as: :index
    post "tasks", to: "tasks#create"
    get "tasks/:id", to: "tasks#show", as: :task
    get "tasks/:id/edit", to: "tasks#edit", as: :edit
    patch "tasks/:id", to: "tasks#update"
    delete "tasks/:id", to: "tasks#destroy", as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]


  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

    <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary'%>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit task</h1>

  <class class="form">
  <%= render 'form', task: @task %>
  </class>

</div>

app/views/tasks/index.html.erb
<div class="container">

  <h1>List of the tasks</h1>
  <br>
  <div id="checkboxes">
    <ul>
      <% @tasks.each do |task| %>
        <li>
          <% if task.completed == true %>
          <span class="glyphicon glyphicon-unchecked"> </span><%=  link_to task.title, task_path(task) %> -
          <span class="glyphicon glyphicon-trash"> </span>
            <%= link_to destroy_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } do %> <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          <% else %>
          <span class="glyphicon glyphicon-check"> </span>
          <%= link_to task.title, task_path(task) %> -
            <%= link_to destroy_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } do %> <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<br><br><br><br>
<hr>

  <div class="btn btn-lg">
    <span class="glyphicon glyphicon-plus"></span>
    <%=link_to "Add a new task", new_path %>
  </div>

</div>

app/views/tasks/new.html.erb
<div class="container">

  <h1>New task</h1>

  <class class="form">
  <%= render 'form', task: @task %>
  </class>

</div>

app/views/tasks/show.html.erb
<div class="container">

  <div class="alert alert-secondary" role="alert">
    <h2><%= @task.title %>
      <button type="button" class="btn btn-default btn-sm" <span class="glyphicon glyphicon-pencil"></span> <%=link_to "Edit this task", edit_path%></h2></button>

    <br><br>
    <p>Details of the task:</p>
    <h3><%= @task.details %></h3>
      <br>
      <% if @task.completed == true %>
        <h5><%= "Your task is completed!" %></h5>
        <% else %>
        <h5><%= "This task is not completed yet" %></h5>
      <% end %>

      <hr>
      <%=link_to "Back to list", index_path%>
  </div>
</div>